### ISSUE TITLE
陀螺仪问题

### ISSUE THREAD

**Issue by LutherShaw8888** [fengtianxi001/MF-PanoramaImage#2]
你好，我使用@three0.125.3版本，但是陀螺仪仍然无效。请问你的项目是如何引用DeviceOrientationControls.js脚本的？你的Demo目前还能正常工作。你是监听deviceorientation事件手动调整相机实现的吗？这个该如何实现？

**Comment by LutherShaw8888** [comment]
你的项目下载到本地后就运行不了了。

**Comment by fengtianxi001** [comment]
你的问题可以看下README, demo使用的版本是"0.133.1"。现在是正常运行的, 陀螺仪如果要在pc浏览器调试的话你自行可以百度下调试方法。
